/**
 * Generates the 60 bundled levels deterministically and writes
 * src/data/bundledLevels.ts. Re-run to regenerate (output is stable per seed).
 *
 *   npx tsx scripts/generate-levels.ts
 *
 * Level layout:
 *   1-20   easy   4x4
 *   21-40  medium 5x5
 *   41-60  hard   6x6
 * Environment gates (see PRODUCT_SPEC §7):
 *   1-10 concert · 11-20 airport · 21-30 subway · 31-40 themepark ·
 *   41-50 school · 51-60 mall
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { generateLevel } from '../src/engine/levelGenerator';
import { solveBoard } from '../src/engine/levelSolver';
import type { GridSize, LevelDefinition } from '../src/types/game';

function gridForNumber(n: number): GridSize {
  if (n <= 20) return 4;
  if (n <= 40) return 5;
  return 6;
}

function envForNumber(n: number): string {
  if (n <= 10) return 'concert';
  if (n <= 20) return 'airport';
  if (n <= 30) return 'subway';
  if (n <= 40) return 'themepark';
  if (n <= 50) return 'school';
  return 'mall';
}

const levels: LevelDefinition[] = [];
for (let n = 1; n <= 60; n++) {
  const gridSize = gridForNumber(n);
  const env = envForNumber(n);
  const level = generateLevel(`bundled:${n}`, n, gridSize, env);
  // Hard assert solvability before committing to the bundle.
  const solved = solveBoard(level.characters, level.gridSize);
  if (!solved.solvable) {
    throw new Error(`Level ${n} generated unsolvable — aborting.`);
  }
  levels.push(level);
  process.stdout.write(
    `  #${n} ${gridSize}x${gridSize} ${env} — ${level.characters.length} chars\n`,
  );
}

const header = `// AUTO-GENERATED by scripts/generate-levels.ts — do not edit by hand.
// 60 solver-validated bundled levels. Regenerate with:
//   npx tsx scripts/generate-levels.ts
import type { LevelDefinition } from '@/types/game';

export const bundledLevels: LevelDefinition[] = ${JSON.stringify(levels, null, 2)};

export function getLevelByNumber(n: number): LevelDefinition | undefined {
  return bundledLevels.find((l) => l.number === n);
}
`;

const outPath = join(process.cwd(), 'src', 'data', 'bundledLevels.ts');
writeFileSync(outPath, header);
console.log(`\nWrote ${levels.length} levels to src/data/bundledLevels.ts`);
